### ISSUE TITLE
Admin Page

### ISSUE THREAD

**Issue by Rakdoslover** [Rakdoslover/Project-5-first#1]
As a **Admin/Site-owner** I can **connect to the admin page** so that **I can create, edit and delete sessions/instructors/events but also see and fulfill orders purchased from the site.**

**Criteria:**

The site administrator can log in and access websites backend.
Admin can create, update and delete the sessions/instructors/events.
Admin can access users purchased items to fulfill the orders.

**Todo:**

 

- [x] Create super users for the admin.
- [x]  Test that admin can create, update and delete sessions/instructors/events.
- [x]  Test that admin can update and delete purchases made by users.
