### ISSUE TITLE
Booking system for events

### ISSUE THREAD

**Issue by Rakdoslover** [Rakdoslover/Project-5-first#10]
As a **user** I can **book a spot on an upcoming event** so that **the user can be sure to get their spot on an event with max capacity**

**Criteria:**

A user be able to ensure that the time/spot they book is theirs, they should also receive somekind of cofirmation (email, ticket etc.)

**Todo:**

- [ ] Create a new app connected to the booking system.
- [ ] Integrate the event calender in the booking system.
- [ ] Connect email confirmation when booking.
- [ ] Connect urls to main app.
