### ISSUE TITLE
View and Bag Sessions

### ISSUE THREAD

**Issue by Rakdoslover** [Rakdoslover/Project-5-first#2]
As a **User** I can **view all sessions available and put the once I like into my bag** so that ** I can purchase the chosen sessions**.

**Criteria:**

The user can view each session individually or in a list.
The user can specify a specific amount of sessions to put in bag.
A function for keeping the bag up to date.

**Todo:**

- [x] Create a view for the collection of sessions at hand.
- [x] Create individual views for the detailed session.
- [x] Connect the Urls.
- [x] Update the appropriate HTML and CSS to get a user friendly view.
- [x] Make a function/button that takes the chosen amount of sessions to the users bag.
