### ISSUE TITLE
View Instructors

### ISSUE THREAD

**Issue by Rakdoslover** [Rakdoslover/Project-5-first#3]
As a **User** I can **find details about each instructor** so that **I know more about each person in charge of the sessions I'm interested in**.

**Criteria:**

The user can access a list of the instructors and their individual information.

**Todo:**

- [x] Create a view which iterates through the instructors.
- [x] Highlight information that might be interesting towards the customer, "sell" their session in the HTML.
- [x] Connect the Urls.
