### ISSUE TITLE
Upcoming Events

### ISSUE THREAD

**Issue by Rakdoslover** [Rakdoslover/Project-5-first#4]
As a **User** I can **see upcoming events** so that **I can plan the events in my calender or invite friends to join me on for a group session.**

**Criteria:**

The users should be able to see the events clearly.
The events should not be hidden behind any "account" wall.

**Todo:**

- [x] Create a view to iterate through created events.
- [x] Update the appropriate HTML and CSS to get a user friendly view.
- [x] Post relevant info first, details through link.
- [x] Connect the Urls.
