### ISSUE TITLE
CRUD Sessions and Events

### ISSUE THREAD

**Issue by Rakdoslover** [Rakdoslover/Project-5-first#5]
As a **Admin** I can **Create, Read, Update and Delete sessions and events from the frontend** so that **I don't need to use the admin backend for every issue**.

**Criteria:**

Admins should be able to create new sessions and events from frontend.
Admins should be able to read, update and delete existing sessions and events from frontend.
Admins should be logged in.

**Todo:**

- [x] Create views for CRUD in views.py of sessions and events.
- [x] Create forms with responding fields for update and create.
- [x] Connect the Urls.
- [x] Update the HTML with buttons for superusers.
- [x] Test the functionality
