### ISSUE TITLE
Admin Login Frontend

### ISSUE THREAD

**Issue by Rakdoslover** [Rakdoslover/Project-5-first#6]
As a **Admin** I can **login from the frontend** so that ** I can CRUD the sessions and events.**

**Criteria.**

Login/logout for admins
CRUD functionality activated upon login.

**Todo:**

- [x] Download and update the Allauth package to match the login/logout format.
- [x] Test that the functionality exists while logged in as admin.
- [x] CRUD a test session/event.
