### ISSUE TITLE
Create Account

### ISSUE THREAD

**Issue by Rakdoslover** [Rakdoslover/Project-5-first#7]
As a **user** I can **create an account** so that ** see my previous orders and update my personal info.**

**Criteria:**

Users submits a valid username and email.
User should be able to log in and out once account is created.
User should be able to read and update personal info and previous orders.

**Todo:**

- [x] Add logic for account registration.
- [x] Add code and logic for signup/login/logout button in navbar.
- [x] Make the personal info form updateable.
- [x] Publish orders purchased by this profiles readable under the profiles.
