### ISSUE TITLE
Purchase Sessions

### ISSUE THREAD

**Issue by Rakdoslover** [Rakdoslover/Project-5-first#8]
As a **user** I can **purchase any amount of sessions** so that ** I can receive the value I pay for.**

**Criteria:**

User can take their bag contents to a checkout.
Payment systems should give users clear and understandable instructions to fulfill the purchase.
A form for the user to fill out relevant information for the site owner to contact the user after fulfilled purchase.

**Todo:**

- [x] Create a checkout view that takes in the bag contents as a variable.
- [x] Connect urls.
- [x] Create a form for the user to fill out.
- [x] Iteration that show each item in the bag and the subtotal/grandtotal.
- [x] Simple but clear buttons that guides the user through the purchase.
- [x] Implement a payment system (Stripe) that deals with the purchase.
- [x] Success screen for the user, and if logged in, a order creation under the profile.
