### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by Rakdoslover** [Rakdoslover/Project-5-first#9]
As a **User** I can **contact the business** so that **I/we can contact and/or book sessions with the instructors**

**Criteria:**

The user can contact the business through the information found on the page.

**Todo:**

- [x] Create a new app for the page.
- [x] Update the appropriate HTML and CSS to get a user friendly view.
- [x] Connect urls to the main app.
